name: Android CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fix gradlew line endings
        run: |
          sed -i 's/\r$//' gradlew
          chmod +x gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle (skip ALL ktlint tasks)
        run: |
          ./gradlew build --no-daemon \
            -x ktlintCheck \
            -x ktlintKotlinScriptCheck \
            -x ktlintMainSourceSetCheck \
            -x ktlintDebugSourceSetCheck \
            -x ktlintReleaseSourceSetCheck \
            -x ktlintAndroidTestSourceSetCheck \
            -x ktlintTestSourceSetCheck

      - name: Run tests
        run: ./gradlew test --no-daemon

      - name: Run detekt
        run: ./gradlew detekt --no-daemon